apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: bigzaza/argocd:300b97b08182f123533f8eecfd09d8a6fdd2c6dd
        name: solar-system
        ports: 
        - containerPort: 80
