apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: bigzaza/argocd:a20a69a7a3fc7cc0abf2819e88fc37f7f000a9fe
        name: solar-system
        ports: 
        - containerPort: 80
