apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: bigzaza/argocd:a6b5612fe7aaf5fc1369c9d1e006300dd71b1bc5
        name: solar-system
        ports: 
        - containerPort: 80
