apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: bigzaza/argocd:0fafacc867bb00d6539ac2d6a52bc71bf391d364
        name: solar-system
        ports: 
        - containerPort: 80
