apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: bigzaza/argocd:d5f6a02e8526a33fd9d75642ffbf7e75d57bf2f7
        name: solar-system
        ports: 
        - containerPort: 80
